name: vendus
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  uuid: ^3.0.4
  sqflite: ^2.3.0
  path: ^1.8.3
  moor: ^4.6.1+1
  fl_chart: ^0.36.0 # Check for the latest version on pub.dev



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/Vendus_dark_logo.png
    - images/Vendus_light_logo.png